name: hyperflaw
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - pip=23.3.2
  - conda-forge::numpy==1.26.3
  - conda-forge::mkl==2024.0.0
  - pytorch::pytorch==1.10.1
  - pytorch:torchvision==0.11.2
  - pytorch:torchaudio==0.10.1
  - conda-forge::cudatoolkit=11.3
  - conda-forge::pytorch-lightning=1.5.2
  - conda-forge::wandb=0.16.2
  - conda-forge::scikit-learn=1.4.0
  - conda-forge::opencv=4.7.0
  - conda-forge::pandas=2.2.0
  - conda-forge::seaborn=0.13.2
  - conda-forge::setuptools=59.5.0
  - pip:
    - hypll==0.1.0
